name: todoapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  linter: ^1.26.0
  logger: ^1.1.0
  provider: ^6.0.3

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  localization: ^2.1.0
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  uuid: ^3.0.6
  path_provider: ^2.0.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logging: ^1.0.2

dev_dependencies:
  hive_generator: ^1.1.3
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1
  flutter_svg: ^1.1.2


  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
          style: normal