on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.5'
      - run: flutter packages get
      - run: flutter format --dry-run
      - run: flutter analyze --no-pub --no-congratulate --no-fatal-infos
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - run: flutter build apk --release
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.TOKENTODOAPP}}
      - name: Deploy
        if: (github.base_ref == 'master' && github.event_name == 'pull_request')
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          release_notes: "a new version"
          file: build/app/outputs/apk/release/app-release.apk